# Generated by Django 3.2.2 on 2024-05-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintMS', '0004_complaint_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='first_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
